name: Combined Frontend and Backend CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  frontend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x, 20.x ]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: week5/week5_practice/ci-practice/frontend/package-lock.json

      - run: npm ci
        working-directory: week5/week5_practice/ci-practice/frontend

      - run: npm run build --if-present
        working-directory: week5/week5_practice/ci-practice/frontend

      - run: npm test
        working-directory: week5/week5_practice/ci-practice/frontend

      - name: Notify Discord
        if: always()
        run: |
          STATUS="Failed"
          if [ "${{ job.status }}" == "success" ]; then
            STATUS="Succeeded"
          fi
          
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"GitHub Actions job **${{ github.job }}** in version **${{ matrix.node-version }}**  finished with status: $STATUS in repo: ${{ github.repository }}\"}" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}


  backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x gradlew
        working-directory: week5/week5_practice/ci-practice/backend

      - name: Build backend with Gradle
        run: ./gradlew build
        working-directory: week5/week5_practice/ci-practice/backend

      - name: Run backend tests
        run: ./gradlew test
        working-directory: week5/week5_practice/ci-practice/backend


      - name: Upload backend artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifacts
          path: week5/week5_practice/ci-practice/backend/build/libs

  success-message:
    runs-on: ubuntu-latest
    needs: [ frontend, backend ]

    steps:
      - name: Echo success message
        run: echo "Both frontend and backend CI/CD flows completed successfully!"
