name: Node.js CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: week5/week5_practice/ci-practice/package-lock.json

    - run: npm ci
      working-directory: week5/week5_practice/ci-practice

    - run: npm run build --if-present
      working-directory: week5/week5_practice/ci-practice

    - run: npm test
      working-directory: week5/week5_practice/ci-practice
      
  artifacts:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - run: mkdir -p artifact
      working-directory: week5/week5_practice/ci-practice
      
    - run: echo hello > artifact/world.txt
      working-directory: week5/week5_practice/ci-practice
      
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: week5/week5_practice/ci-practice/artifact/world.txt

