name: Deploy App to Azure VM

on:
  push:
    branches:
      - main

env:
  MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
  MYSQL_USER: ${{ secrets.MYSQL_USER }}
  MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
  MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.REMOTE_PORT }} ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
        shell: bash

      - name: Rsync files to Azure VM
        run: |
          rsync -avz -e "ssh -p ${{ secrets.REMOTE_PORT }} -i ~/.ssh/id_rsa" ./week7/week7_practice/ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/${{ secrets.REMOTE_USER }}/app/
        shell: bash

      - name: Run docker-compose up remotely
        run: |
          ssh -p ${{ secrets.REMOTE_PORT }} -i ~/.ssh/id_rsa ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} \
            "cd /home/${{ secrets.REMOTE_USER }}/project && docker compose up -d"
        shell: bash

      - name: Collect docker-compose logs remotely
        run: |
          ssh -p ${{ secrets.REMOTE_PORT }} -i ~/.ssh/id_rsa ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} \
            "cd /home/${{ secrets.REMOTE_USER }}/project && docker compose logs --no-color" > ./deploy-to-azure-vm.txt
        shell: bash
        continue-on-error: true

      - name: Upload deployment logs artifact
        uses: actions/upload-artifact@v4
        with:
          name: deploy-to-azure-vm-logs
          path: ./deploy-to-azure-vm.txt

      - name: Notify Slack on success
        if: success()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          slack-message: |
            ✅ Deployment to Azure VM succeeded.
            See deployment logs artifact for details.

      - name: Notify Slack on failure
        if: failure()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          slack-message: |
            ❌ Deployment to Azure VM failed.
            See deployment logs artifact for details.
